language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
after_deploy:
  - now --token $NOW_TOKEN rm alias --safe --yes
